### ISSUE TITLE
JavaScript if else gets indented wrong

### ISSUE THREAD

**Issue by wittrup** [ffes/indentbyfold#14]
Basically the same as issue #1 and #2, but for JS.

```JS
function onNodeConnectionChange(args) {
    if (entity.isInboundNodeConnected(0)) {
        storage.inputOpen = entity.getInboundNodeLevel(0);
    } else {  // <--- Expected
        storage.inputOpen = true;
    };
};
```
get Reindented to:

```JS
function onNodeConnectionChange(args) {
    if (entity.isInboundNodeConnected(0)) {
        storage.inputOpen = entity.getInboundNodeLevel(0);
        } else {  // <--- Unexpected
        storage.inputOpen = true;
    };
};
```

**Comment by wittrup** [comment]
### Quick-fix
In N++ this can be fixed after _Reindent File_ by search and replace all

Find what: `\t(} else {)`
Replace with: `\1`
Search Mode: Regular expression

**Comment by ffes** [comment]
The whole idea of IdentByFold is to use the folding points that Scintilla recognizes and tell N++ to indent the code at those points. This makes the plugin almost completely language independent! When you look at the `[+]` or `[-]` in the left margin you can see want those parsers thinks are foldable lines. 

FYI: Scintilla is the editor component that N++ is built around.

All the points mentioned in this issue, in #1 and in #12 those folding point don't exist at the points you all mention in those issues. There simply is no `[+]` or `[-]` at those lines.

The simple answer to your question is: Scintilla doesn't understand your code style and it unlikely that I will fix it.

There are two solutions to this issue. The best would be that the folding points recognized by Scintilla are improved. This is an upstream fix in Scintilla that I have no intention of developing.

The other is that the plugin will need to get languages specific solutions for those languages that can recognize this special cases and work around the limitations of Scintilla. And I don't see myself doing that any time soon.

To give a little background. The plugin was originally developed by Ben Bluemel in 2011. He abandoned it a little later and all I did was make sure it is still around today because I like it the way it is. It suits my coding style and it works quite good enough for me. The code has changed very little, in its core it is still Ben's code. It doesn't have much comment and there are many points in the code where I haven't got a clue what exactly is happening.

I really need to dig in to try and solve a problem that I never run in to myself because I don't use that code style or those languages. Knowing that I have many other projects (online and offline) that need my attention I don't see that happen any time soon.

That all being said, I understand your problem. I obviously will gladly review and merge pull requests that solve these problem.

**Comment by ffes** [comment]
I turned the comment above into a FAQ in the docs:  
https://indentbyfold.readthedocs.io/en/latest/faq.html#faq-if-else

I am closing this one as a dup of #1
